### ISSUE TITLE
error running `npm run demo`: register is not a function

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1739]
After successfully running `npm run migrate:up` and `npm run init`:

```
$ npm run demo

> openopps-platform@0.15.0 demo /home/openopps/app
> node ./tools/demo.js

DATABASE_URL = postgresql://...<readacted>
importing: /home/openopps/app/tools/demo-data/users.csv
err:  TypeError: register is not a function
    at Promise.all.users.map (/home/openopps/app/tools/lib/dbTools.js:80:20)
    at Array.map (<anonymous>)
    at Object.importUsersFromFile (/home/openopps/app/tools/lib/dbTools.js:79:30)
    at dbTools.checkTableSetup.then (/home/openopps/app/tools/demo.js:6:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

Note: on visual inspection, DATABASE_URL appears to be correct

**Comment by ultrasaurus** [comment]
I just ran through the setup instructions and `npm run demo` ran successfully without error and seems to have added data to the database.  Updated description to be more specific to the error in the description.  

Assuming this got fixed with some other change in the last few months, so I'm closing this issue.

**Comment by ultrasaurus** [comment]
Looking at related bug #1560 -- this may be related to setting an alternate DATABASE_URL, rather than running locally.  If that is the issue, then this could be re-opened with more specific repro steps.
