### ISSUE TITLE
npm run migrate:up fails with "Error querying for tasks with an invalid restrict column value"

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#2331]
this happened from an old db, then a dropped the db and recreated and got the same error.

Repro steps:

```
dropdb midas
createdb midas
migrate:up
```

full text of the error (along with context of the migrations that worked just before the error):
```
[INFO] Processed migration 20180507135119-add-careers-to-tagentity
[INFO] Processed migration 20180507140634-add-sort-to-task-tagentities
[WARN] Using unknown data type CHARACTER VARYING
[WARN] Using unknown data type INTEGER
[WARN] Using unknown data type TIMESTAMP WITH TIME ZONE
[WARN] Using unknown data type TIMESTAMP WITH TIME ZONE
[INFO] Processed migration 20180518160731-add-announcement-table
[INFO] Processed migration 20180521192015-initialize-null-agency-data-column
[INFO] Found 0 parent child relationships for agencies.
[INFO] Completed parent child relationships for agencies.
[INFO] Processed migration 20180522115351-create-parent-abbreviation-on-agency-data-column
[ERROR] Error querying for tasks with an invalid restrict column value { error: operator does not exist: json ->> boolean
    at Connection.parseE (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 197,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',
  position: '157',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '722',
  routine: 'op_error' }
[ERROR] error: operator does not exist: json ->> boolean
    at Connection.parseE (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/sallen/src/openopps/openopps-platform/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

**Comment by ultrasaurus** [comment]
isolated this issue by testing the syntax in node REPL:

on the command line, just type `node` then...

```
const pgp = require('pg-promise')();
const connection = process.env.DATABASE_URL || require('./database.json').dev;
const db = pgp(connection);
const _ = require('underscore');

queries.findTasks = "select json(restrict)->>\'name\' is null from task";
db.any(queries.findTasks).then(async (rows) => { console.log(rows) })
```

result:
```
> (node:15054) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): error: operator does not exist: json ->> boolean
```

with parens:
```
queries.findTasks = "select (json(restrict)->>\'name\') is null from task";
db.any(queries.findTasks).then(async (rows) => { console.log(rows) })
```

result:
```
> []
```

**Comment by ultrasaurus** [comment]
I'm not sure how this could have worked before, the only difference I can think of is that I'm using a more recent version of postgres than the install instructions (10.3).  In any case, the addition of parentheses and in one case explicit `text` type fixed this issue for me.  I will submit a PR.
