### ISSUE TITLE
ElasticSearch setup information in INSTALL.md

### ISSUE THREAD

**Issue by DavidEBest** [openopps/openopps-platform#4498]
### Who
Open Source users/redeployers

### What
Documentation describing the appropriate ElasticSearch setup for local machine installation.

### Why
I am working with a group to redeploy the application to a state. I am working through the install directions now and running into issues with the ElasticSearch component. Specifically, I am getting a `mapper_parsing_exception` on several templates. The documentation doesn't mention ElasticSearch at all, so I just did a basic install in OS X via Homebrew

### Acceptance Criteria
The INSTALL.md describes how to install and configure ElasticSearch for OpenOpps.

### Related Tickets 
NA

### Mocks
```
Loading...  /Users/dbest/Development/cfd/openopps-platform/config/email.js
{ Error: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]
    at respond (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/Users/dbest/Development/cfd/openopps-platform/node_modules/lodash/lodash.js:4929:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[mapper_parsing_exception] Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]',
  path: '/_template/user_template',
  query: { order: 1, create: false },
  body:
   { error:
      { root_cause: [Array],
        type: 'mapper_parsing_exception',
        reason: 'Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]',
        caused_by: [Object] },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [user : {properties={skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, lastName={normalizer=lowercase, type=keyword}, career={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, agency={properties={name={normalizer=lowercase, type=keyword}, agencyId={type=long}}}, givenName={normalizer=lowercase, type=keyword}, name={normalizer=lowercase, type=keyword}, bio={normalizer=lowercase, type=keyword}, middleName={normalizer=lowercase, type=keyword}, location={properties={country={normalizer=lowercase, type=keyword}, cityName={normalizer=lowercase, type=keyword}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={normalizer=lowercase, type=keyword}}}, id={type=long}, title={normalizer=lowercase, type=keyword}}}]"}},"status":400}',
  toString: [Function],
  toJSON: [Function] }
updated user_template template
{ Error: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]
    at respond (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/dbest/Development/cfd/openopps-platform/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/Users/dbest/Development/cfd/openopps-platform/node_modules/lodash/lodash.js:4929:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[mapper_parsing_exception] Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]',
  path: '/_template/task_template',
  query: { order: 1, create: false },
  body:
   { error:
      { root_cause: [Array],
        type: 'mapper_parsing_exception',
        reason: 'Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]',
        caused_by: [Object] },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [task : {properties={taskLength={normalizer=lowercase, type=keyword}, keywords={normalizer=lowercase, type=keyword}, isInternship={type=long}, postingLocation={properties={country={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityName={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountry={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, cityCountrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}, countrySubdivision={search_analyzer=lowercase, analyzer=engram_analyzer, type=text}}}, about={type=text}, description={type=text}, locationType={normalizer=lowercase, type=keyword}, office={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, cycle={properties={applyStartDate={type=date}, name={normalizer=lowercase, type=keyword}, applyEndDate={type=date}, id={type=long}}}, timeEstimate={normalizer=lowercase, type=keyword}, skills={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, details={type=text}, id={type=long}, state={normalizer=lowercase, type=keyword}, bureau={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, outcome={type=text}, updatedAt={format=strict_date_optional_time||epoch_millis, type=date}, requester={normalizer=lowercase, type=keyword}, languages={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, taskPeople={normalizer=lowercase, type=keyword}, community={properties={name={normalizer=lowercase, type=keyword}, communityLogo={normalizer=lowercase, type=keyword}, id={type=long}, shortName={normalizer=lowercase, type=keyword}}}, restrictedToAgency={normalizer=lowercase, type=keyword}, postingAgency={normalizer=lowercase, type=keyword}, timeRequired={normalizer=lowercase, type=keyword}, careers={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, series={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, grade={type=long}, acceptingApplicants={type=boolean}, locations={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}, payPlan={properties={name={normalizer=lowercase, type=keyword}, id={type=long}}}}}]"}},"status":400}',
  toString: [Function],
  toJSON: [Function] }
updated task_template template
```

**Comment by bmcorum** [comment]
@DavidEBest where are you guys planning on hosting a the version of this for usage at the state or local government levels. This repository now has very specific business rules and dependencies on USAJOBS. Really needs to be a new repository for usage at lower level of government.

**Comment by DavidEBest** [comment]
@bmcorum It's for the state of California, hosting on AWS (probably).

I understand that there will be a lot of changes and rework to get it functional for someone other than the Federal government. At this point, I am just trying to get the project up and running in a local development environment.

**Comment by bmcorum** [comment]
@DavidEBest the Install.md file is certainly out of date. We all use Windows and I recall most of that was even out of date when OPM received the project. I think most of the discrepancies with the Windows section was mainly due to GSA/18F using Mac or Linux systems. So I would say the Install.md probably needs to be entirely rewritten.

**Comment by DavidEBest** [comment]
@bmcorum I'd be happy to assist with updating it, especially the OS X parts. Do you have any more recent documentation that y'all are using to onboard new developers?

**Comment by bmcorum** [comment]
@DavidEBest the other issue you will likely run into is getting all the data migrations to run since a few of them expect integration with USAJOBS to collect the require enumeration data such as agencies, countries, country subdivisions (state, territory, province), languages, pay plans, etc.

**Comment by bmcorum** [comment]
@DavidEBest let me see what I can find. We tried to simply the process as much as possible. The only other major dependency should be Elasticsearch. I know they have an MSI installer, and should have deb and brew options for Mac and Linux.

**Comment by Nolski** [comment]
@bmcorum, thanks for all of the information here! Do you know roughly when the repository was handed over to OPM? It might be worth one of us (happy to help with this as well) reverting to that commit and running a fork from there.

**Comment by LisaLNelson** [comment]
If I recall correctly I think it was the fall of 17.

**Comment by LisaLNelson** [comment]
@Nolski You may be able to start around January 2018 as I think that's when the actual refactor work started. @brice could confirm that. One of the reasons the refactor was done is because the code was in bad shape. GSA had pulled all dev support many months before the move and we held it together by begging & borrowing 18F support when something broke. There were no updates made to the code although 18F colleagues helped with quick fixes when something broke. .

**Comment by Nolski** [comment]
@LisaLNelson I definitely feel your pain :( . I've been in similar situations when R&D teams or vendors like to hand off half baked products to be supported at scale. 

I'll look at reverting the commits and updating from there for now. If the team is interested in a community led effort to disconnect the core openopps code from USAJOBS (as it seems a few folks from CA are looking to do so as well), I'd be happy to look into assisting with that instead of reverting as well :)

**Comment by bmcorum** [comment]
@DavidEBest I may know what your Elasticsearch issue is. So I did fresh install this morning on a windows machine and discovered that installing the lastest version of Elastic will not work. We are using Elasticsearch 5.6 because that is all that is offered currently by Cloud.gov. Once you have 5.6 installed you will need to publish your first opportunity for search to work (this seems strange to me now, but something with the index does not like not having at least some data). Also I ran into a few errors running all the data migrations and need to make a few edits to two script files. I will try to get them checked in shortly. I also had better results by install db-migrate globally then running db-migrate -c 1 to just run the initial up script then ran the npm run init then run db-migrate up once again to run all remaining migrations. The load bureau script will throw and error the first time through so just run db-migrate up one final time and it should complete all migrations. Not sure why the bureau migration fails the first time. Only thing I can think of is that it is trying to insert the data and the table schema has yet to update in memory.

**Comment by amprokop** [comment]
@Nolski — thanks for chiming in! Wanted to comment on the following just for an FYI:

> I'll look at reverting the commits and updating from there for now

We were advised by @LisaLNelson that from 2018-present  there were potentially substantial bugfixes made. Our CA friends had previously stood up a fork from 2018 but advised us that that version of the code had some issues. We're looking into this too and will be sure to advise on our conclusion.

**Comment by amprokop** [comment]
@Nolski - wanted to follow up-

With @bmcorum's two recent tweaks to migrations as well as installing ElasticSearch 5.6, @DavidEBest and I were both able to get it up and running. 

https://github.com/chhsinnovation/openopps-platform/pull/7
